// NOTE: The whole implementation temporarily assumes that the input is valid at now, except for the unsafe functions.

///|
pub fn parse_pointer(str : String) -> JsonPointer {
  let str = str.trim_space()
  if str == "" {
    // raise InvalidPath(src=str)
    panic()
  }
  match str[0] {
    '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' =>
      unsafe_parse_relative_pointer(str)
    _ => unsafe_parse_abosulute_pointer(str)
  }
}

///| @alert unsafe "Panic if invalid invalid string received"
pub fn unsafe_parse_abosulute_pointer(str : String) -> JsonPointer {
  guard not(str.is_blank())
  let root = match str.index_of("#") {
    -1 => 0
    i => i
  }
  let url = str.substring(end=root)
  AbsolutePointer(id=url, str.substring(start=root).split("/").collect())
}

///| @alert unsafe "Panic if invalid invalid string received"
pub fn unsafe_parse_relative_pointer(str : String) -> JsonPointer {
  guard not(str.is_blank())
  RelativePointer(str.split("/").collect())
}

///|
pub fn resolve_pointer(self : JsonPointer, path : JsonPointer) -> JsonPointer {
  match (self, path) {
    (AbsolutePointer(id~, _), AbsolutePointer(id="", subpath)) =>
      AbsolutePointer(id~, subpath)
    (AbsolutePointer(id=id1, _), AbsolutePointer(id=id2, subpath)) =>
      if id2.starts_with("..") {
        // TODO: Handle ".." in the path
        AbsolutePointer(id=id1 + id2, subpath)
      } else if id2.contains("://") {
        AbsolutePointer(id=id2, subpath)
      } else {
        let i = id1.last_index_of("/")
        AbsolutePointer(id=id1.substring(end=i + 1) + id2, subpath)
      }
    _ => panic()
  }
}

///|
pub fn resolve_value(self : JsonPointer, json : Json) -> Json!Error {
  self |> ignore
  match self {
    AbsolutePointer(id=_, path) as pointer => {
      assert_eq!(path[0], "#")
      loop path[:], path.length(), json {
        ["#"], 1, val => break val
        ["#", ..], _, val => continue path[1:], path[1:].length(), val
        [key], 1, val =>
          break val
            .value(key)
            .or_error!(KeyNotFound(key~, path=pointer, src=json, val))
        [key, ..] as p, _, val =>
          continue p[1:],
            p[1:].length(),
            val
            .value(key)
            .or_error!(KeyNotFound(key~, path=pointer, src=json, val))
        _, _, _ => panic()
      }
    }
    RelativePointer(_path) as _pointer => panic()
  }
}

///|
pub impl Show for JsonPointer with output(self, logger) -> Unit {
  match self {
    AbsolutePointer(id~, path) => {
      Logger::write_string(logger, id)
      Logger::write_string(logger, String::concat(path, separator="/"))
    }
    RelativePointer(path) =>
      Logger::write_string(logger, String::concat(path, separator="/"))
  }
}
